<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.A4GTMg.' shared service.

return $this->privates['.service_locator.A4GTMg.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contactoRepository' => ['privates', 'App\\Repository\\ContactoRepository', 'getContactoRepositoryService.php', true],
]);
