<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fQi914O' shared service.

return $this->privates['.service_locator.fQi914O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'blog' => ['privates', '.errored..service_locator.fQi914O.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.fQi914O": it references class "App\\Entity\\Blog" but no such service exists.'],
]);
