<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PVLy0pL' shared service.

return $this->privates['.service_locator.PVLy0pL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'reserva' => ['privates', '.errored..service_locator.PVLy0pL.App\\Entity\\Reserva', NULL, 'Cannot autowire service ".service_locator.PVLy0pL": it references class "App\\Entity\\Reserva" but no such service exists.'],
]);
