<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NXu3Rh_' shared service.

return $this->privates['.service_locator.NXu3Rh_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'camaRepository' => ['privates', 'App\\Repository\\CamaRepository', 'getCamaRepositoryService.php', true],
]);
