<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aoMEtqn' shared service.

return $this->privates['.service_locator.aoMEtqn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'servicioadicional' => ['privates', '.errored..service_locator.aoMEtqn.App\\Entity\\Servicioadicional', NULL, 'Cannot autowire service ".service_locator.aoMEtqn": it references class "App\\Entity\\Servicioadicional" but no such service exists.'],
]);
