<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6w14uVb' shared service.

return $this->privates['.service_locator.6w14uVb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pisoRepository' => ['privates', 'App\\Repository\\PisoRepository', 'getPisoRepositoryService.php', true],
]);
