<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._mPqi0M' shared service.

return $this->privates['.service_locator._mPqi0M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'piso' => ['privates', '.errored..service_locator._mPqi0M.App\\Entity\\Piso', NULL, 'Cannot autowire service ".service_locator._mPqi0M": it references class "App\\Entity\\Piso" but no such service exists.'],
]);
