<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Q3561m1' shared service.

return $this->privates['.service_locator.Q3561m1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'centrosaludRepository' => ['privates', 'App\\Repository\\CentrosaludRepository', 'getCentrosaludRepositoryService.php', true],
]);
