<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fYgSZ4d' shared service.

return $this->privates['.service_locator.fYgSZ4d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'blogRepository' => ['privates', 'App\\Repository\\BlogRepository', 'getBlogRepositoryService.php', true],
]);
