<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3VjqZmG' shared service.

return $this->privates['.service_locator.3VjqZmG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'reservaRepository' => ['privates', 'App\\Repository\\ReservaRepository', 'getReservaRepositoryService.php', true],
]);
