<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Tg652B8' shared service.

return $this->privates['.service_locator.Tg652B8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'centrosalud' => ['privates', '.errored..service_locator.Tg652B8.App\\Entity\\Centrosalud', NULL, 'Cannot autowire service ".service_locator.Tg652B8": it references class "App\\Entity\\Centrosalud" but no such service exists.'],
]);
