<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4fyERRh' shared service.

return $this->privates['.service_locator.4fyERRh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'zona' => ['privates', '.errored..service_locator.4fyERRh.App\\Entity\\Zona', NULL, 'Cannot autowire service ".service_locator.4fyERRh": it references class "App\\Entity\\Zona" but no such service exists.'],
]);
