<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.h4PkN8t' shared service.

return $this->privates['.service_locator.h4PkN8t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'servicio' => ['privates', '.errored..service_locator.h4PkN8t.App\\Entity\\Servicios', NULL, 'Cannot autowire service ".service_locator.h4PkN8t": it references class "App\\Entity\\Servicios" but no such service exists.'],
]);
