<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WPl_6iw' shared service.

return $this->privates['.service_locator.WPl_6iw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serviciosRepository' => ['privates', 'App\\Repository\\ServiciosRepository', 'getServiciosRepositoryService.php', true],
]);
