<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UTsgbkJ' shared service.

return $this->privates['.service_locator.UTsgbkJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'supermercadoRepository' => ['privates', 'App\\Repository\\SupermercadoRepository', 'getSupermercadoRepositoryService.php', true],
]);
