<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7M.BmZN' shared service.

return $this->privates['.service_locator.7M.BmZN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'habitacionesRepository' => ['privates', 'App\\Repository\\HabitacionesRepository', 'getHabitacionesRepositoryService.php', true],
]);
