<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Enj1oFM' shared service.

return $this->privates['.service_locator.Enj1oFM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'universidad' => ['privates', '.errored..service_locator.Enj1oFM.App\\Entity\\Universidad', NULL, 'Cannot autowire service ".service_locator.Enj1oFM": it references class "App\\Entity\\Universidad" but no such service exists.'],
]);
