<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HXbSsf9' shared service.

return $this->privates['.service_locator.HXbSsf9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'casavacacional' => ['privates', '.errored..service_locator.HXbSsf9.App\\Entity\\Casavacacional', NULL, 'Cannot autowire service ".service_locator.HXbSsf9": it references class "App\\Entity\\Casavacacional" but no such service exists.'],
]);
