<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.fQi914O.App\Entity\Blog' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Blog.php';

return $this->privates['.errored..service_locator.fQi914O.App\Entity\Blog'] = new \App\Entity\Blog();
