<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Command\\DebugCommand.php';

$this->privates['console.command.form_debug'] = $instance = new \Symfony\Component\Form\Command\DebugCommand(($this->privates['form.registry'] ?? $this->load('getForm_RegistryService.php')), [0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type', 1 => 'App\\Form', 2 => 'Symfony\\Bridge\\Doctrine\\Form\\Type'], [0 => 'App\\Form\\BlogType', 1 => 'App\\Form\\CamaType', 2 => 'App\\Form\\Casavacacional1Type', 3 => 'App\\Form\\CasavacacionalType', 4 => 'App\\Form\\CentrosaludType', 5 => 'App\\Form\\ClienteType', 6 => 'App\\Form\\Contacto1Type', 7 => 'App\\Form\\ContactoType', 8 => 'App\\Form\\Habitaciones1Type', 9 => 'App\\Form\\HabitacionesType', 10 => 'App\\Form\\PisoType', 11 => 'App\\Form\\Reserva1Type', 12 => 'App\\Form\\ReservaType', 13 => 'App\\Form\\ServicioadicionalType', 14 => 'App\\Form\\ServiciosType', 15 => 'App\\Form\\SupermercadoType', 16 => 'App\\Form\\UniversidadType', 17 => 'App\\Form\\ZonaType', 18 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType', 19 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType', 20 => 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType'], [0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\TransformationFailureExtension', 1 => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\Type\\FormTypeHttpFoundationExtension', 2 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension', 3 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension', 4 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension', 5 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\UploadValidatorExtension', 6 => 'Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension', 7 => 'Symfony\\Component\\Form\\Extension\\DataCollector\\Type\\DataCollectorTypeExtension'], [0 => 'Symfony\\Component\\Form\\Extension\\Validator\\ValidatorTypeGuesser', 1 => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser']);

$instance->setName('debug:form');

return $instance;
