<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormRegistryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormRegistry.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormExtensionInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Extension\\DependencyInjection\\DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Extension\\DataCollector\\Proxy\\ResolvedTypeFactoryDataCollectorProxy.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Form\\BlogType' => ['privates', 'App\\Form\\BlogType', 'getBlogTypeService.php', true],
    'App\\Form\\CamaType' => ['privates', 'App\\Form\\CamaType', 'getCamaTypeService.php', true],
    'App\\Form\\Casavacacional1Type' => ['privates', 'App\\Form\\Casavacacional1Type', 'getCasavacacional1TypeService.php', true],
    'App\\Form\\CasavacacionalType' => ['privates', 'App\\Form\\CasavacacionalType', 'getCasavacacionalTypeService.php', true],
    'App\\Form\\CentrosaludType' => ['privates', 'App\\Form\\CentrosaludType', 'getCentrosaludTypeService.php', true],
    'App\\Form\\ClienteType' => ['privates', 'App\\Form\\ClienteType', 'getClienteTypeService.php', true],
    'App\\Form\\Contacto1Type' => ['privates', 'App\\Form\\Contacto1Type', 'getContacto1TypeService.php', true],
    'App\\Form\\ContactoType' => ['privates', 'App\\Form\\ContactoType', 'getContactoTypeService.php', true],
    'App\\Form\\Habitaciones1Type' => ['privates', 'App\\Form\\Habitaciones1Type', 'getHabitaciones1TypeService.php', true],
    'App\\Form\\HabitacionesType' => ['privates', 'App\\Form\\HabitacionesType', 'getHabitacionesTypeService.php', true],
    'App\\Form\\PisoType' => ['privates', 'App\\Form\\PisoType', 'getPisoTypeService.php', true],
    'App\\Form\\Reserva1Type' => ['privates', 'App\\Form\\Reserva1Type', 'getReserva1TypeService.php', true],
    'App\\Form\\ReservaType' => ['privates', 'App\\Form\\ReservaType', 'getReservaTypeService.php', true],
    'App\\Form\\ServicioadicionalType' => ['privates', 'App\\Form\\ServicioadicionalType', 'getServicioadicionalTypeService.php', true],
    'App\\Form\\ServiciosType' => ['privates', 'App\\Form\\ServiciosType', 'getServiciosTypeService.php', true],
    'App\\Form\\SupermercadoType' => ['privates', 'App\\Form\\SupermercadoType', 'getSupermercadoTypeService.php', true],
    'App\\Form\\UniversidadType' => ['privates', 'App\\Form\\UniversidadType', 'getUniversidadTypeService.php', true],
    'App\\Form\\ZonaType' => ['privates', 'App\\Form\\ZonaType', 'getZonaTypeService.php', true],
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.transformation_failure_handling'] ?? $this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
    yield 5 => ($this->privates['form.type_extension.form.data_collector'] ?? $this->load('getForm_TypeExtension_Form_DataCollectorService.php'));
}, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? ($this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? ($this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($this->privates['data_collector.form'] ?? $this->getDataCollector_FormService())));
