<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBZCaLYN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBZCaLYN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBZCaLYN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBZCaLYN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBZCaLYN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BZCaLYN',
    'container.build_id' => '61c4c599',
    'container.build_time' => 1556477597,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBZCaLYN');
